swagger: "2.0"
info:
  title: "XSS Test"
  description: "<div style=background:url('javascript:alert(document.domain)')>"
  version: "1.0"
paths:
  /test:
    get:
      summary: "Test"
      responses:
        '200':
          description: "OK"
